ARG BASE_IMAGE=ubuntu:20.04
FROM ${BASE_IMAGE} AS base-image

LABEL org.opencontainers.image.authors="luc.coupal.1@ulaval.ca"
ARG DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-c"]

# install development utilities
RUN apt-get update \
    && apt-get install --assume-yes --no-install-recommends \
        apt-utils \
        sudo \
        gnupg2 \
        lsb-release \
        cmake \
        build-essential \
        curl \
        wget \
        ca-certificates \
        git \
        libusb-dev \
        usbutils \
        vim \
        tree \
        zip gzip tar unzip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR "/"

#RUN useradd -m docker && echo "docker:docker" | chpasswd && adduser docker sudo
#USER docker

COPY vm_software_install_ros1 "/vm_software_install_ros1"
COPY utilities "/utilities"
COPY .git "/.git"


WORKDIR vm_software_install_ros1
RUN chmod +x install_percep3d_software_ros1.bash
RUN bash install_percep3d_software_ros1.bash
CMD ["bash"]
